const PDFDocument = require('pdfkit');

const formatAmount = (amount) => `Rs. ${Number(amount || 0).toLocaleString('en-IN')}`;

const writeRow = (document, label, amount, emphasis = false) => {
	document.font(emphasis ? 'Helvetica-Bold' : 'Helvetica').text(label, 72, document.y, { continued: true }).text(formatAmount(amount), { align: 'right' });
};

const createPayslipPdf = ({ payslip, employee }) => {
	const document = new PDFDocument({ margin: 56, size: 'A4' });
	document.fillColor('#17352f').fontSize(22).font('Helvetica-Bold').text('PeoplePay360');
	document.moveDown(0.4).fillColor('#6a7d77').fontSize(10).font('Helvetica').text('PAYSLIP');
	document.moveDown(1).fillColor('#17352f').fontSize(16).font('Helvetica-Bold').text(`${employee?.firstName || ''} ${employee?.lastName || ''}`.trim() || payslip.employeeId);
	document.fillColor('#6a7d77').fontSize(10).font('Helvetica').text(`Employee ID: ${payslip.employeeId}`);
	document.text(`Period: ${new Date(`${payslip.period}-01`).toLocaleString('en-US', { month: 'long', year: 'numeric' })}`);
	document.moveDown(1).strokeColor('#d9eadd').moveTo(56, document.y).lineTo(539, document.y).stroke();
	document.moveDown(0.7).fillColor('#17352f').fontSize(12).font('Helvetica-Bold').text('Salary Breakdown');
	document.moveDown(0.5);
	for (const line of payslip.lines.filter((item) => ['Basic', 'Allowance'].includes(item.category))) writeRow(document, line.name, line.amount);
	document.moveDown(0.4).strokeColor('#d9eadd').moveTo(72, document.y).lineTo(523, document.y).stroke();
	document.moveDown(0.4); writeRow(document, 'Gross Salary', payslip.grossSalary, true);
	document.moveDown(0.8);
	for (const line of payslip.lines.filter((item) => ['Deduction', 'Tax'].includes(item.category))) writeRow(document, line.name, line.amount);
	document.moveDown(0.4).strokeColor('#d9eadd').moveTo(72, document.y).lineTo(523, document.y).stroke();
	document.moveDown(0.4); writeRow(document, 'Net Salary', payslip.netSalary, true);
	document.moveDown(2).fillColor('#81948e').fontSize(9).font('Helvetica').text('Generated by PeoplePay360 payroll processing.');
	return document;
};

const createPayslipPdfBuffer = ({ payslip, employee }) => new Promise((resolve, reject) => {
	const document = createPayslipPdf({ payslip, employee });
	const chunks = [];
	document.on('data', (chunk) => chunks.push(chunk));
	document.on('end', () => resolve(Buffer.concat(chunks)));
	document.on('error', reject);
	document.end();
});

const createPersonalReportPdfBuffer = ({ employee, reportType, attendance = [], leaveRequests = [] }) => new Promise((resolve, reject) => {
	const document = new PDFDocument({ margin: 56, size: 'A4' });
	const chunks = [];
	document.on('data', (chunk) => chunks.push(chunk));
	document.on('end', () => resolve(Buffer.concat(chunks)));
	document.on('error', reject);

	document.fillColor('#17352f').fontSize(22).font('Helvetica-Bold').text('PeoplePay360');
	document.moveDown(0.4).fillColor('#6a7d77').fontSize(10).font('Helvetica').text(`${reportType.toUpperCase()} REPORT`);
	document.moveDown(1).fillColor('#17352f').fontSize(16).font('Helvetica-Bold').text(`${employee.firstName} ${employee.lastName}`);
	document.fillColor('#6a7d77').fontSize(10).font('Helvetica').text(`Employee ID: ${employee.employeeId}`);
	document.text(`Department: ${employee.department}`);
	document.moveDown(1).strokeColor('#d9eadd').moveTo(56, document.y).lineTo(539, document.y).stroke();
	document.moveDown(0.7).fillColor('#17352f').fontSize(12).font('Helvetica-Bold').text(reportType === 'attendance' ? 'Attendance Records' : 'Leave Requests');
	document.moveDown(0.5).fontSize(10).font('Helvetica');

	if (reportType === 'attendance') {
		for (const record of attendance) {
			document.fillColor('#29423d').text(`${new Date(record.date).toLocaleDateString('en-IN')}  |  ${record.checkIn || '—'} - ${record.checkOut || '—'}  |  ${record.workedHours || 0} hours  |  ${record.status}`);
			document.fillColor('#6a7d77').text(`Remarks: ${record.remarks || '—'}`).moveDown(0.45);
		}
	} else {
		for (const request of leaveRequests) {
			document.fillColor('#29423d').text(`${request.leaveTypeId?.name || 'Leave'}  |  ${new Date(request.fromDate).toLocaleDateString('en-IN')} - ${new Date(request.toDate).toLocaleDateString('en-IN')}  |  ${request.days} days  |  ${request.status}`);
			document.fillColor('#6a7d77').text(`Reason: ${request.reason || '—'}`).moveDown(0.45);
		}
	}

	if ((reportType === 'attendance' ? attendance : leaveRequests).length === 0) {
		document.fillColor('#6a7d77').text('No records found.');
	}
	document.moveDown(1).fillColor('#81948e').fontSize(9).text('Generated by PeoplePay360.');
	document.end();
});

const createReportPdfBuffer = ({ title, subtitle, sections }) => new Promise((resolve, reject) => {
	const document = new PDFDocument({ margin: 56, size: 'A4' });
	const chunks = [];
	document.on('data', (chunk) => chunks.push(chunk));
	document.on('end', () => resolve(Buffer.concat(chunks)));
	document.on('error', reject);
	document.fillColor('#17352f').fontSize(22).font('Helvetica-Bold').text('PeoplePay360');
	document.moveDown(0.4).fillColor('#6a7d77').fontSize(10).font('Helvetica').text('REPORT');
	document.moveDown(1).fillColor('#17352f').fontSize(18).font('Helvetica-Bold').text(title);
	document.fillColor('#6a7d77').fontSize(10).font('Helvetica').text(subtitle || 'Generated from PeoplePay360 reports.');
	document.moveDown(1).strokeColor('#d9eadd').moveTo(56, document.y).lineTo(539, document.y).stroke();
	for (const section of sections) {
		document.moveDown(0.7).fillColor('#17352f').fontSize(12).font('Helvetica-Bold').text(section.heading);
		document.moveDown(0.35).fontSize(9).font('Helvetica');
		for (const row of section.rows) document.fillColor('#29423d').text(row).moveDown(0.18);
		if (!section.rows.length) document.fillColor('#6a7d77').text('No records found.');
	}
	document.moveDown(1).fillColor('#81948e').fontSize(9).text('Generated by PeoplePay360.');
	document.end();
});

module.exports = { createPayslipPdf, createPayslipPdfBuffer, createPersonalReportPdfBuffer, createReportPdfBuffer };
